### ISSUE TITLE
new returns for downloadSong function

### ISSUE THREAD

**Issue by HenrrySilva** [joshunrau/ytdl-mp3#3]
The DownloadSong function could return some options beyond of audio name, example an  type ReadableStream.

example

```
const ytdlMp3 = new YtdlMp3(URL_VIDEL);

ytdlMp3.downloadSong();
ytdlMp3.readStream();
```

**Comment by joshunrau** [comment]
This is a good idea. I was considering doing a refactor one of these days, but I just don't have the time at the moment. If I end up doing that, I will implement. In the mean time, feel free to make a PR I will merge this into main for sure if it is helpful for you and others.

**Comment by joshunrau** [comment]
This is not happening for the time being unless someone makes a PR
