### ISSUE TITLE
Failed to fetch info for video with URL

### ISSUE THREAD

**Issue by dench1k** [joshunrau/ytdl-mp3#36]
Tried to update for the new version but without success. ytdl-mp3 is installed globally. It worked great 2 weeks ago at least. Do you have some thoughts what can be the problem?
Thanks in advance

ytdl-mp3 https://www.youtube.com/watch?v=PN-ih2G79TU
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
C:\Users\admin\AppData\Roaming\npm\node_modules\ytdl-mp3\dist\index.js:233
      throw new Error(`Failed to fetch info for video with URL: ${url}`);
            ^

Error: Failed to fetch info for video with URL: https://www.youtube.com/watch?v=PN-ih2G79TU
    at C:\Users\admin\AppData\Roaming\npm\node_modules\ytdl-mp3\dist\index.js:233:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.0.0

**Comment by joshunrau** [comment]
Hi, this is caused by [an issue](https://github.com/fent/node-ytdl-core/issues/1204) with `ytdl-core`. As a temporary workaround, I downgraded the dependency. Try updating to the latest version and trying again. Let me know if it is fixed!

**Comment by dench1k** [comment]
I updated the package and it works, although downloading goes longer than it was before. Thanks, Joshua!

**Comment by joshunrau** [comment]
> I updated the package and it works, although downloading goes longer than it was before. Thanks, Joshua!

Yeah I noticed that too unfortunately. Not sure why it is. 

In any case, I will update back to the new version when they fix it which should hopefully speed it up again.
