### ISSUE TITLE
Any way to remove console log?

### ISSUE THREAD

**Issue by adihanifsdr** [joshunrau/ytdl-mp3#64]
It always outputting something like
```Done! Output file: tmp/music/m89GTfifrrM/spin_and_burst.mp3``

How can i get rid of this? Any options to disable logging to console?

**Comment by joshunrau** [comment]
Nope, not currently. If you want to make a PR, you could add a silent mode. Otherwise, I will leave this open and next time I add something I will see if I can add this in.

**Comment by joshunrau** [comment]
Added by @ShaquilleSadiq
